import type { Metadata } from 'next'
import '../globals.css'

export const metadata: Metadata = {
    title: 'Teslo Shop',
    description: 'Generated by create next app'
}

export default function AuthLayout({ children }: Readonly<{ children: React.ReactNode }>) {

    return (

        <main className='min-h-screen bg-gray-500'>
            { children }
        </main>

    )

}